import Redirect from "@/components/auth/redirect";
import { NotifyContainer } from "@/components/utils/toast";
import "@/styles/globals.sass";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "primeicons/primeicons.css";
import "primereact/resources/primereact.min.css";
import "primereact/resources/themes/lara-light-indigo/theme.css"; //theme
import "/node_modules/primeflex/primeflex.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Redirect />
        <NotifyContainer />
        {children}
      </body>
    </html>
  );
}
